graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 200
         y 35
      ]
   ]
   node [
      id 1
      graphics [
         x 350
         y 120
      ]
   ]
   node [
      id 2
      graphics [
         x 280
         y 250
      ]
   ]
   node [
      id 3
      graphics [
         x 120
         y 250
      ]
   ]
   node [
      id 4
      graphics [
         x 50
         y 120
      ]
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 1
      target 2
   ]
   edge [
      source 2
      target 3
   ]
   edge [
      source 3
      target 4
   ]
   edge [
      source 4
      target 0
   ]
]