graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 400
         y 30
      ]
   ]
   node [
      id 1
      graphics [
         x 260
         y 135
      ]
   ]
   node [
      id 2
      graphics [
         x 535
         y 135
      ]
   ]
   node [
      id 3
      graphics [
         x 400
         y 135
      ]
   ]
   node [
      id 4
      graphics [
         x 260
         y 255
      ]
   ]
   node [
      id 5
      graphics [
         x 535
         y 255
      ]
   ]
   node [
      id 6
      graphics [
         x 400
         y 255
      ]
   ]
   node [
      id 7
      graphics [
         x 400
         y 385
      ]
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 0
      target 3
   ]
   edge [
      source 0
      target 2
   ]
   edge [
      source 1
      target 6
   ]
   edge [
      source 2
      target 6
   ]
   edge [
      source 3
      target 6
   ]
   edge [
      source 1
      target 4
   ]
   edge [
      source 2
      target 5
   ]
   edge [
      source 4
      target 7
   ]
   edge [
      source 6
      target 7
   ]
   edge [
      source 5
      target 7
   ]
]